import { Providers } from "@/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppbarClient from "@/components/AppbarClient";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/auth";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Paytm",
  description: "Generated by turbo",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <Providers session={session}>
        <body className={inter.className}>
          <div className="min-h-screen">
            <AppbarClient />
            <Toaster />
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
