import { Providers } from "@/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/auth";
import Root from "./root";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Paytm",
  description: "Generated by turbo",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <Providers session={session}>
        <body className={inter.className}>
          <Root>{children}</Root>
        </body>
      </Providers>
    </html>
  );
}
