name: "Build and Deploy to Docker Hub"

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Prepare Dockerfile
        run: cp ./docker/Dockerfile.user ./Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jstgrwup/paytm:latest

      - name: Verify Image
        run: docker pull jstgrwup/paytm:latest
